News article
tmampa/New-York-Times-Article pull request #1
Opened 2021-03-23 18:36 UTC by tmampa

2021-03-24 17:01 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @tmampa  :wave:

__You've really done well so far. Here're the major highlights of this PR:__

- All your linter checks are running and passing successfully :100: 
- You have a descriptive PR title and summary :ok_hand: 
- Your Readme looks great! :+1:
- Your webpage contents are well structured :+1: 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] The `display: flex` rule occurs in about eight(8) different parts of your CSS blocks. You can avoid this repetition by declaring a block (i.e. .flex { display: flex }) and apply the flex class to those elements you want to display as flex. Always keep your code DRY
- [ ] Kindly remove the bullets for all list items in the bottom navigation section. You can check the original page and ensure to implement similar behavior on your page.
- [ ] The `Suggested newsletters for you`, `Most popular` and `More in Space and Astronomy` sections are completely missing from your page. Please add them.
![conflict](https://user-images.githubusercontent.com/26856491/112351717-6b839500-8cca-11eb-8dc2-c0ce14ef7bf9.png)

- [ ] The `Editor`s Picks` section is also missing. Kindly add it. If you cannot find this section using firefox, please use a different browser (e.g. chrome) and you should see it.
![conflict](https://user-images.githubusercontent.com/26856491/112352019-b4d3e480-8cca-11eb-8a19-c72d595350d6.png)

- [ ] Do not forget to use <a href="https://www.w3schools.com/tags/tag_aside.asp" rel="nofollow noreferrer noopener" target="_blank"><code>&lt;aside&gt;</code> tag</a> for <code>Editor's picks</code> section on the righmost side. (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png">screenshot</a> from <a href="https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/" rel="nofollow noreferrer noopener" target="_blank">Pathwright</a>)
- [ ] Check my inline comments below for other changes.

**[ OPTIONAL CHANGES ]**

- [ ] You should be careful with overusing the `id` attribute as a CSS selector. If your page is well cascaded and class selectors are used appropriately, I believe you do not have to use that `id` attribute as a CSS selector. This is because `id` selectors have higher precedence than class selectors and if care is not taken, it can mess up your styling in large projects. Check [this article](https://speckyboy.com/good-bad-css-practices/) for other CSS bad practices.

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

**REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project.**

_**Please make the required changes and submit another review request when you are done.**_

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-26 12:27 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @tmampa  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] There is a long white space between the navigation bar and the main content of the page, kindly remove that space and make sure that the right side editor's pick is floating on the rightmost part of the view port

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-03-26 14-23-31](https://user-images.githubusercontent.com/56886064/112630933-f38aab80-8e3e-11eb-8f55-1df605c02a2a.png) ![Screenshot from 2021-03-26 14-23-51](https://user-images.githubusercontent.com/56886064/112630985-00a79a80-8e3f-11eb-82ce-3ee034c1c10f.png) | ![Screenshot from 2021-03-26 14-26-07](https://user-images.githubusercontent.com/56886064/112631213-42d0dc00-8e3f-11eb-9cab-2f12bef988de.png) |

:point_right: Could you see the difference :question: :question: :question: 
___

### :warning: Warning: According to the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 1 code review left for this project, make sure that you implement all of the required changes carefully and request another review while you are sure that it's ready. :warning: 

_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-26 12:27 UTC, descholar-ceo commented on .gitignore
> +package-lock.json
[required] Remove this `package-lock.json` file from the gitignore file

2021-03-26 12:27 UTC, descholar-ceo commented on .gitignore
> +vscode
[required] it should be `.vscode` instead `vscode` => notice the dot at the beginning

2021-03-26 12:27 UTC, descholar-ceo commented on .vscode/settings.json
> +}
[required] You should remove this `.vscode` folder from your repo. To achieve that you can run `git rm -rf .vscode` and add `.vscode` in gitignore and then commit the changes

2021-03-26 12:27 UTC, descholar-ceo commented on index.html
> +              </div>
[required] the boxes in this section, I mean image and text should be links, this means they use anchor tags. Check carefully the original page

2021-03-26 14:03 UTC, tmampa commented on .gitignore
> +package-lock.json
@descholar-ceo I fixed all the requested changes, however I cannot see the white space between my nav and the rest of the page, could you please check for me if you can see it and if I'm ready to submit another review

2021-03-26 14:14 UTC, tmampa commented
@descholar-ceo  fixed all the requested changes, however I cannot see the white space between my nav and the rest of the page, could you please check for me if you can see it and if I'm ready to submit another review
![Screenshot from 2021-03-26 16-03-25](https://user-images.githubusercontent.com/67906597/112643247-d3fa7f80-8e4c-11eb-9ea1-b01dceb5c1ef.png)

2021-03-26 15:42 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @tmampa :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-26 15:46 UTC, merged